2019/April/community_news.md
Signed-off-by: Chandan Kumar <raukadah@gmail.com>
=> Added April PythonPune community newsletter

2019/May/community_news.md
=> Added May PythonPune 2019 community newsletter

.github/ISSUE_TEMPLATE/propose-a-talk.md
- Should make the process of submitting a new talk very easy
=> Add issue template for proposing a talk

.travis.yml, 2019/March/community_news.md, README.md
Signed-off-by: Nikhil Dhandre <nik.digitronik@live.com>
- PR introduces Travis fro sanity checks
- Fix some links
fixed #6
=> Travis for quality check

2019/June/community_news.md
=> Added June 2019 Newsletter

2019/June/README.md
Add talks from June Python Pune meetups.
=> Update June meetup talks

2019/July/community_news.md
=> Add July 2019 Newsletter

2019/August/community_news.md
=> Added Aug 2019 community newsletter

CODE_OF_CONDUCT.md, LICENSE, README.md
- Add CC BY-SA 4.0 license to the repository
- https://creativecommons.org/licenses/by-sa/4.0/
- Add Code of Conduct for the PythonPune meetup group
- Adopted from Pyladies CoC https://www.pyladies.com/CodeOfConduct/
- Update README.md with more details about meetup
=> Add README.md, Code of Conduct and LICENSE

2019/September/community_news.md
=> Added Sep 2019 community newsletter

2019/September/README.md, README.md
closes #44 closes #19 closes #45
=> Add details of September 2019 meetup

.github/ISSUE_TEMPLATE/propose-a-talk.md
Not adding difficulty level intentionally for now.
=> Add duration section for propose-a-talk.md issue template

2019/October/community_news.md
=> Added Oct 2019 newsletter

2019/October/README.md, README.md
Closes #52, closes #55, closes #53, closes #59
=> Add details of October 2019 meetup

2019/November/community_news.md
=> Added Nov PythonPune newsletter

2019/November/README.md, README.md
Closes #63 closes #63 closes #65
=> Add details of November 2019 meetup

2019/December/community_news.md
=> Added Dec 2019 Newsletter

2020/January/community_news.md
=> Added Jan 2020 community newsletter

2020/February/community_news.md
=> Added Feb 2020 community news

Makefile, README.md, templates/README.md, templates/community_news.md
- This makes it easy to add new entries for a month
- Update the README as well
=> Add Makefile and templates for newsletter and event summary

2019/December/README.md, 2020/February/README.md, 2020/January/README.md, README.md
Closes #75, closes #51, closes #77 and closes #73
=> Add summaries for December 2019, January and February 2020

2020/March/README.md, 2020/March/community_news.md
Add meetup details in README.md
Add community newsletter in community_news.md
=> March: Add community_news

2020/March/community_news.md
Add Cloud-Native Rejekts in Upcoming events in & around
=> community_news.md: Add Cloud Native Rejekts

.github/workflows/main.yml, 2020/March/README.md, 2020/March/community_news.md
We will add the missing slides later. Individual videos are processed and scheduled to be published at 21:00 IST today.
Fixes #82, fixes #86
=> Add details of March 2020 meetup

2020/April/README.md, 2020/April/community_news.md
=> Added April community Newsletter 2020

2020/May/community_news.md
May 2020 PythonPune newsletter.
Fixes #98
=> May 2020 PythonPune newsletter.

2020/June/README.md, 2020/June/community_news.md
=> Added June community newsletter

2020/July/community_news.md
=> Add July 2020 community newsletter

.github/ISSUE_TEMPLATE/newsletter_box.md, .github/workflows/newsletter-issue.yml, .github/workflows/sanity-checks.yml
This month issue we forgot to create :) so decided to automate this.
- It will create newsletter collection issue At 00:30 on day-of-month 1.
- It will add notification to IRC/Telegram about issue open
example:
- https://github.com/digitronik/meetup-talks/issues/2
- https://github.com/digitronik/meetup-talks/actions/runs/181304681
part of #15
=> Automating newsletter issue

content/2020/August/community_news.md
=> Added Aug Community Newsletter

content/2020/October/community_news.md
Compiled Newsletter for the month of October 2020 with the help of #121 and #123 .
=> Compiled Newsletter for the month of October 2020.

README.md, archetypes/event.md, content/2020/August/README.md, content/2020/July/README.md, content/2020/October/README.md, content/2020/September/README.md
Fixes #106, Fixes #107, Fixes #108, Fixes #112, Fixes #113, Fixes #125, Fixes #128
=> Add summaries for July to October 2020 meetups

content/2020/November/community_news.md
=> Add Nov 2020 PythonPune Newsletter

content/2020/December/community_news.md
=> Added December 2020 newsletter

.github/workflows/newsletter-issue.yml, .github/workflows/notifications.yml
=> Notifications of newsletter comment and talk-proposal to irc

content/2021/January/community_news.md
=> Added Janurary 21 Community Newsletter

README.md, content/2020/December/README.md, content/2020/March/README.md, content/2020/November/README.md, content/2021/January/README.md
Closes #122 closes #135 closes #139
=> Add summaries for November, December 2020 and January 2021 meetup

content/2021/February/community_news.md
=> Added Feb 2021 newsletter

content/2021/March/community_news.md
=> Added Mar 2021 Newsletter

config.yaml
=> Update Copyright year to 2021

content/2021/April/README.md, content/2021/February/README.md
=> Add summaries for February and April

config.yaml
Added some new ways to connect to PythonPune:
- Add LinkedIn page URL in footer
- Add Telegram group in "join us" section.
=> New ways to connect

config.yaml, go.mod, go.sum
Floating button is easily accessible and always on top button that is
currently pointing to telegram group.
=> Add floating button config
